JobSeekingClient/Pages/Accounts/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ClientRepository.Service;
using ClientRepository.Service.Implementation;
using ClientRepository;
using ClientRepository.Models;

namespace JobSeekingClient.Pages.Accounts
{
    public class CreateModel : PageModel
    {
        private readonly IRoleService _roleService;
        private readonly IAccountService _accountService;

        public CreateModel(IAccountService accountService, IRoleService roleService)
        {
            _accountService = accountService;
            _roleService = roleService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            ViewData["RoleId"] = new SelectList(await _roleService.GetListAsync(path: StoredURI.Role, token: HttpContext.Session.GetString("token")), "Id", "Name");
            return Page();
        }

        [BindProperty]
        public AccountModel Account { get; set; } = null!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid)
            {
                return Page();
            }
            await _accountService.Add(Account, path: StoredURI.Account, token: null);
            return RedirectToPage("/Accounts/IndexAdmin");
        }
    }
}

JobSeekingClient/Pages/Categories/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using AppCore;
using AppCore.Models;
using ClientRepository.Service;
using ClientRepository.Models;
using ClientRepository.Utils;
using ClientRepository;

namespace JobSeekingClient.Pages.Categories
{
    public class CreateModel : PageModel
    {
        private readonly ICategoryService _categoryService;

        public CreateModel(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public CategoryModel Category { get; set; }
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid)
            {
                return Page();
            }
            string? token = HttpContext.Session.GetString("token");
            int? role = HttpContext.Session.GetInt32("Role");
            if (string.IsNullOrEmpty(token))
            {
                return RedirectToPage("../Auth/Login");
            }
            if (role != (int)AccountRole.Administrator)
            {
                return RedirectToPage("../Home");
            }

            var category = await _categoryService.GetModelAsync(expression: c => c.Name.ToLower().Equals(Category.Name.ToLower())
                                                               , path: StoredURI.Category + "/" + Category.Id.ToString(), token: token);
            if (category != null)
            {
                ViewData["Error"] = "Already exist category name!";
                return Page();
            }

            await _categoryService.Add(Category, path: StoredURI.Category, token: token);
            return RedirectToPage("./Index");
        }
    }
}

JobSeekingClient/Pages/Interviews/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ClientRepository.Service;
using ClientRepository.Models;
using AppCore.Models;
using ClientRepository;

namespace JobSeekingClient.Pages.Interviews
{
    public class CreateModel : PageModel
    {
        private readonly IInterviewService _interviewService;

        public CreateModel(IInterviewService interviewService)
        {
            _interviewService= interviewService;
        }
        public async Task<IActionResult> OnGetAsync(string date, int slotId, int applicationId)
        {
            Interview = new InterviewModel()
            {
                ApplicationId = applicationId,
                SlotId = slotId,
                Date = DateTime.Parse(date),
            };
            string? token = HttpContext.Session.GetString("token");
            var interviewers = await _interviewService.GetAvailableInterviewers(slotId, DateOnly.Parse(date), Interview.ApplicationId, token);
            ViewData["InterviewerId"] = new SelectList(interviewers, nameof(AccountModel.Id), nameof(AccountModel.Email));
            return Page();
        }

        [BindProperty]
        public InterviewModel Interview { get; set; } = null!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid)
            {
                return await OnGetAsync(Interview.Date.ToString(), Interview.SlotId, Interview.ApplicationId);
            }
            string? token = HttpContext.Session.GetString("token");
            await _interviewService.Add(Interview, path: StoredURI.Interviews, token: token);

            return RedirectToPage("/Applications/Details", new { id = Interview.ApplicationId });
        }
    }
}

JobSeekingClient/Pages/Levels/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using AppCore;
using AppCore.Models;
using ClientRepository.Service;
using ClientRepository.Utils;
using ClientRepository.Models;
using ClientRepository;

namespace JobSeekingClient.Pages.Levels
{
    public class CreateModel : PageModel
    {
        private readonly ILevelService _levelService;

        public CreateModel(ILevelService levelService)
        {
            _levelService = levelService;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public LevelModel Level { get; set; }
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            string? token = HttpContext.Session.GetString("token");
            int? role = HttpContext.Session.GetInt32("Role");
            if (string.IsNullOrEmpty(token))
            {
                return RedirectToPage("../Auth/Login");
            }
            if (role != (int)AccountRole.Administrator)
            {
                return RedirectToPage("../Home");
            }

            var level = await _levelService.GetModelAsync(expression: c => c.Name.ToLower().Equals(Level.Name.ToLower())
                                                               , path: StoredURI.Level + "/" + Level.Id.ToString(), token: token);
            if (level != null)
            {
                ViewData["Error"] = "Already exist level name!";
                return Page();
            }

            await _levelService.Add(Level, path: StoredURI.Level, token: token);
            return RedirectToPage("./Index");
        }
    }
}

JobSeekingClient/Pages/Post/PostDetail.cshtml.cs
using ClientRepository;
using ClientRepository.Models;
using ClientRepository.Service;
using ClientRepository.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Diagnostics;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;

namespace JobSeekingClient.Pages
{
    public class PostDetailModel : PageModel
    {
        public PostDTO Post { get; set; }

        private readonly IConfiguration config;

        private readonly IPostService postService;

        private readonly IApplicationService applicationService;
        private readonly ICategoryService _categoryService;
        private readonly ILevelService _levelService;
        private readonly ILocationService _locationService;
        private readonly IPostSkillService _postSkillService;
        private readonly IUserSkillService _userSkillService;
        private readonly IInterviewService _interviewService;
        public string Category { get; set; }

        public string Location { get; set; }

        public string Level { get; set; }

        public bool CanApply { get; set; } = true;

        public ApplicationModel OldApplication { get; set; }

        public IEnumerable<PostSkillModel> PostSkills { get; set; } 

        public PostDetailModel(IConfiguration config, IPostService postService, IApplicationService applicationService, 
            ICategoryService categoryService, ILevelService levelService, ILocationService locationService, IPostSkillService postSkillService,
            IUserSkillService userSkillService, IInterviewService interviewService)
        {
            this.config = config;
            this.postService = postService;
            this.applicationService = applicationService;
            this._categoryService = categoryService;
            _levelService = levelService;
            _locationService = locationService;
            _postSkillService = postSkillService;
            _userSkillService = userSkillService;
            _interviewService = interviewService;
        }
        public async Task<IActionResult> OnGet(int id)
        {
            string? token = HttpContext.Session.GetString("token");
            if (string.IsNullOrEmpty(token))
            {
                return RedirectToPage("../Auth/Login");
            }
            int? role = HttpContext.Session.GetInt32("Role");
            int? userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("../Auth/Login");
            }
            if(role == (int)AccountRole.Administrator)
            {
                return RedirectToPage("/Home");
            }
            Post = postService.GetModelAsync(id).Result;
            if(Post != null)
            {
                var category = await _categoryService.GetModelAsync(path: StoredURI.Category + $"/{Post.CategoryId}", token: token);
                var level = await _levelService.GetModelAsync(path: StoredURI.Level + $"/{Post.LevelId}", token: token);
                var location = await _locationService.GetModelAsync(path: StoredURI.Location + $"/{Post.LocationId}", token: token);
                if (category == null || level == null || location == null)
                {
                    return RedirectToPage("../Home");
                }
                Category = category.Name;
                Location = location.Name;
                Level = level.Name;
                PostSkills = await _postSkillService.GetListAsync(path: StoredURI.PostSkill + $"/{id}", token: token);
                if (PostSkills == null || PostSkills.Count() == 0)
                {
                    ViewData["Error"] = "Post has no skills to apply!";
                    return Page();
                }
                if(DateTime.Now.Date.CompareTo(Post.StartDate.Date) < 0 || DateTime.Now.Date.CompareTo(Post.EndDate.Date) > 0)
                {
                    CanApply = false;
                }
            }
            var applications = await applicationService.GetListAsync(path: StoredURI.Application + $"/ApplicationNonInterview/ApplicantId/{userId}", token: token);
            if(applications != null && applications.Count() == 2)
            {
                bool alreadyApplyPost = false;
                foreach(var application in applications)
                {
                    if(application.PostId == id)
                    {
                        alreadyApplyPost = true;
                    }
                }
                if (!alreadyApplyPost)
                {
                    CanApply = false;
                }
            }
            if (role != (int)AccountRole.Applicant)
            {
                CanApply = false;
            }
            applications = await applicationService.GetListAsync(path: StoredURI.Application + $"/Get/ApplicantId/{userId}/PostId/{id}", token: token);
            if (applications != null)
            {
                if (applications.Count > 0)
                {
                    foreach (var application in applications)
                    {
                        var interviews = await _interviewService.GetListAsync(expression: i => i.ApplicationId == application.Id && i.IsDeleted == false, path: StoredURI.Interviews, token: token);
                        if(interviews != null && interviews.Count() > 0)
                        {
                            ViewData["Error"] = "You have interview for this post!";
                            CanApply = false;
                            break;
                        }
                        if (OldApplication == null)
                        {
                            OldApplication = application;
                        }
                       
                        if (application.Status != null)
                        {
                            CanApply = false;
                            break;
                        }
                    }
                }
            }
            return Page();
        }

        public async Task<IActionResult> OnPostApply(int id, IFormFile cvFile)
        {
            string? token = HttpContext.Session.GetString("token");
            int? role = HttpContext.Session.GetInt32("Role");
            if (string.IsNullOrEmpty(token))
            {
                return RedirectToPage("../Auth/Login");
            }
            int? userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToPage("../Auth/Login");
            }
            if (role != (int)AccountRole.Applicant)
            {
                ViewData["Error"] = "Need to be applicant account to apply cv!";
                await OnGet(id);
                return Page();
            }
            if (cvFile == null)
            {
                ViewData["Error"] = "CV file not located!";
                await OnGet(id);
                return Page();
            }
            if(!cvFile.FileName.ToLower().Contains(".pdf"))
            {
                ViewData["Error"] = "CV file must be pdf extension!";
                await OnGet(id);
                return Page();
            }
            var postSkillModels = await _postSkillService.GetListAsync(path: StoredURI.PostSkill + $"/{id}", token: token);
            if(postSkillModels == null || postSkillModels.Count() == 0)
            {
                ViewData["Error"] = "Post has no skills to apply!";
                await OnGet(id);
                return Page();
            }
            var userSkills = await _userSkillService.GetListAsync(path: StoredURI.UserSkill + $"/{userId}", token: token);
            if (userSkills == null || userSkills.Count == 0)
            {
                ViewData["Error"] = "You have no skills required!";
                await OnGet(id);
                return Page();
            }
            bool userContainSkill = false;
            foreach(var postSkill in postSkillModels)
            {
                foreach (var userSkill in userSkills)
                {
                    if (postSkill.SkillId == userSkill.SkillId)
                    {
                        userContainSkill = true;
                        break;
                    }
                }
            }
            if(!userContainSkill)
            {
                ViewData["Error"] = "You don't have post skills required!";
                await OnGet(id);
                return Page();
            }
            var applications = await applicationService.GetListAsync(path: StoredURI.Application + $"/Get/ApplicantId/{userId}/PostId/{id}", token: token);
            bool isResubmit = false;
            if (applications != null)
            {
                if (applications.Count > 0)
                {
                    foreach (var application in applications)
                    {
                        var interviews = await _interviewService.GetListAsync(expression: i => i.ApplicationId == application.Id && i.IsDeleted == false, path: StoredURI.Interviews, token: token);
                        if (interviews != null && interviews.Count() > 0)
                        {
                            ViewData["Error"] = "You have interview for this post!";
                            await OnGet(id);
                            return Page();
                        }
                        if (application.Status != null)
                        {
                            ViewData["Error"] = "You already interviewed this post!";
                            await OnGet(id);
                            return Page();
                        }
                        application.IsDeleted = true;
                        var res = await applicationService.Update(application, path: StoredURI.Application + $"/{application.Id}", token: token);

JobSeekingClient/Pages/Post/Create.cshtml
@page
@model JobSeekingClient.Pages.Post.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Post</h4>
<hr />
@{
    if (!string.IsNullOrEmpty(ViewBag.Error))
    {
        <div class="alert alert-danger" role="alert">
            @ViewBag.Error
        </div>
    }
    if (!string.IsNullOrEmpty(ViewBag.Success))
    {
        <div class="alert alert-success" role="alert">
            @ViewBag.Success
        </div>
    }
}
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Post.Title" class="control-label"></label>
                <input asp-for="Post.Title" class="form-control" />
                <span asp-validation-for="Post.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Post.Description" class="control-label"></label>
                <input asp-for="Post.Description" class="form-control" />
                <span asp-validation-for="Post.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Post.CategoryId" class="control-label"></label>
                <select asp-for="Post.CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Post.LocationId" class="control-label"></label>
                <select asp-for="Post.LocationId" class ="form-control" asp-items="ViewBag.LocationId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Post.LevelId" class="control-label"></label>
                <select asp-for="Post.LevelId" class ="form-control" asp-items="ViewBag.LevelId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Post.StartDate" class="control-label"></label>
                <input asp-for="Post.StartDate" class="form-control" />
                <span asp-validation-for="Post.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Post.EndDate" class="control-label"></label>
                <input asp-for="Post.EndDate" class="form-control" />
                <span asp-validation-for="Post.EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Post.Amount" class="control-label"></label>
                <input asp-for="Post.Amount" class="form-control"/>
                <span asp-validation-for="Post.Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                Skills:
                <br /><br/>
                <select name="SkillIds" asp-items="Model.Skills" multiple="multiple" class="listbox"></select>
                <br /><br/>               
            </div>
            <input type="hidden" class="form-check-input" asp-for="Post.Status" value="true" />
            <input type="hidden" class="form-check-input" asp-for="Post.CreateDate" value="@DateTime.Now" />
            <input type="hidden" class="form-check-input" asp-for="Post.Id" value="-1" />
            <input type="hidden" class="form-check-input" asp-for="Post.IsDeleted" value="false" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href=" https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <link href=" https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
    <script src=" https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $('.listbox').multiselect({
                includeSelectAllOption: true
            });
        });
    </script>
}

JobSeekingClient/Pages/Post/PostDelete.cshtml
@page
@model JobSeekingClient.Pages.Post.PostDeleteModel

@{
    ViewData["Title"] = "PostDelete";
}

<h1>PostDelete</h1>
<h3>Are you sure you want to delete this?</h3>
<p class="text-danger">@ViewData["Message"]</p>
<h4>Post Detail</h4>
<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.Title)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Post.Title)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.Location)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Post.Location.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.Level)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Post.Level.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.CreateDate)
    </dt>
    <dd class="col-sm-10">
        @Convert.ToDateTime(Model.Post.CreateDate).ToString("dd/MM/yyyy")
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.Description)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Post.Description)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.Amount)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Post.Amount)
    </dd>
</dl>
    
    <form method="post">
        <input type="hidden" asp-for="Post.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="/Home">Back to List</a>
    </form>
</div>

JobSeekingClient/Pages/Post/PostDetail.cshtml
@page "/Post/{id:int}"
@using System.Net
@using ClientRepository.Utils
@model JobSeekingClient.Pages.PostDetailModel
@{
    ViewData["Title"] = "Post Detail";
}
@{
    if (!string.IsNullOrEmpty(ViewBag.Error))
    {
        <div class="alert alert-danger" role="alert">
            @ViewBag.Error
        </div>
    }
    if (!string.IsNullOrEmpty(ViewBag.Success))
    {
        <div class="alert alert-success" role="alert">
            @ViewBag.Success
        </div>
    }
}
<style>
    .skill-item {
        display: flex;
        flex-wrap: wrap;
    }

        .skill-item span {
            display: inline-block;
            margin: 5px;
            border: 1px solid black;
            padding: 5px;
            border-radius: 5px;
        }

</style>
<h4>Post Detail</h4>
<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.Title)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Post.Title)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Category)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Category)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.PostSkills)
    </dt>
    <dd class="col-sm-10 skill-item">
        @{
            if (Model.PostSkills != null && Model.PostSkills.Count() > 0)
            {
                foreach (var postSkill in Model.PostSkills)
                {
                    <span>@postSkill.SkillName</span>
                }
            }
        }
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Location)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Location)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Level)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Level)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.CreateDate)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Post.CreateDate, "MM/dd/yyyy")
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.StartDate)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Post.StartDate, "MM/dd/yyyy")
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.EndDate)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Post.EndDate, "MM/dd/yyyy")
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.Description)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Post.Description)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Post.Amount)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Post.Amount)
    </dd>
</dl>
@{
    if (Model.OldApplication != null)
    {
        string url = $"../CV/{Model.OldApplication.Id}";
        <a href="@url"> View Applied CV</a>
    }
    if (Model.CanApply)
    {
        <form method="post" , enctype="multipart/form-data">
            <div class="mb-3">
                <label for="formFile" class="form-label">CV File</label>
                <input class="form-control" type="file" accept=".pdf" name="cvFile" id="formFile">
            </div>
            <input class="btn btn-primary" asp-page-handler="Apply" type="submit" value="Apply">
        </form>
    }
}